version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=erp_demo
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      - POSTGRES_HOST=db
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data: